language: node_js
services:
  - mongodb
addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
node_js:
  - '8'
  - '10'
  - '12'
  - '14'
before_script:
  - npm install
notifications:
  email: false
